/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * YAML configuration accepted by sizeup
 */
export interface Configuration {
  /**
   * category that will be assigned to a pull request depending on its score
   *
   * @minItems 1
   */
  categories?: [
    {
      /**
       * name of the category
       */
      name: string;
      /**
       * exclusive upper bound on the score that a pull request must have to be assigned this category
       */
      lt?: number;
      [k: string]: unknown;
    },
    ...{
      /**
       * name of the category
       */
      name: string;
      /**
       * exclusive upper bound on the score that a pull request must have to be assigned this category
       */
      lt?: number;
      [k: string]: unknown;
    }[]
  ];
  scoring?:
    | {
        /**
         * shorthand for a specific scoring formula
         */
        strategy: "default";
        [k: string]: unknown;
      }
    | {
        /**
         * an expression, written in prefix-notation, that describes how to combine features to produce a score
         */
        formula: string;
        [k: string]: unknown;
      };
  /**
   * glob expressions defining file patterns that should be considered as tests during the scoring process
   */
  tests?: string[];
  /**
   * glob expressions defining file patterns that are ignored in the scoring process
   */
  ignored?: string[];
  [k: string]: unknown;
}
